[package]
name = "MiniBrew"
version = "0.4.0"
edition = "2024"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "5.0"
indicatif = "0.17"
ureq = "2.5"
open = "5"
